version: "3.8"

services:
  cockroach:
    image: cockroachdb/cockroach:v22.1.5
    command: start-single-node --insecure
    ports:
      # postgres
      - 26257:26257
      # ui
      - 8081:8080
    volumes:
      - "./dev/database:/cockroach/cockroach-data"

  gorse:
    image: zhenghaoz/gorse-in-one:0.4.5
    command: >
      -c /etc/gorse/config.toml
    environment:
      GORSE_DATA_STORE: postgres://root@cockroach:26257/gorse?sslmode=disable
      # GORSE_CACHE_STORE: postgres://root@cockroach:26257/gorse?sslmode=disable
      GORSE_CACHE_STORE: redis://dragonfly:6379/
      # GORSE_DATA_STORE: postgresql://root@cockroach:26257/defaultdb?sslmode=disable
      # GORSE_CACHE_STORE: postgresql://root@cockroach:26257/defaultdb?sslmode=disable
    ports:
      # ui & api
      - "8088:8088"
    volumes:
      - ./gorse/config.toml:/etc/gorse/config.toml
    depends_on:
      - cockroach
      - dragonfly

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - ./dev/dragonfly:/data
    command:
      - "--hz=0"

  meilisearch:
    image: getmeili/meilisearch:v0.28
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: MASTER_KEY
      MEILI_ENV: ${MEILI_ENV:-development}
    volumes:
      - "./dev/meili_data:/meili_data"
