import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Navbar from "../components/navbar";

const Dashboard: NextPage = () => {
  const { data, isLoading } = trpc.useQuery([
    "example.hello",
    { text: "from tRPC" },
  ]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
};

export default Dashboard;
